_format_version: "1.1"
services:
- connect_timeout: 60000
  host: app
  name: app
  port: 5000
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: app-route
    path_handling: v0
    paths:
    - /app
    plugins:
    - config:
        bearer_only: "yes"
        client_id: kong
        client_secret: 6PgfQpXa8fTGdKN5FA9PL11tpirggQTv
        discovery: http://localhost:8000/auth/realms/experimental/.well-known/openid-configuration
        filters: null
        introspection_endpoint: http://localhost:8000/auth/realms/experimental/protocol/openid-connect/token/introspect
        introspection_endpoint_auth_method: null
        logout_path: /logout
        realm: experimental
        recovery_page_path: null
        redirect_after_logout_uri: /
        redirect_uri_path: null
        response_type: code
        scope: openid
        session_secret: null
        ssl_verify: "no"
        token_endpoint_auth_method: client_secret_post
      enabled: true
      name: oidc
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  host: keycloak
  name: base
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: auth
    path_handling: v0
    paths:
    - /auth
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
  write_timeout: 60000
